# Generated by Django 3.2.19 on 2023-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_app', '0002_rename_coordinates_point_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closestpoints',
            name='closest_point',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='closestpoints',
            name='original_points',
            field=models.CharField(max_length=200),
        ),
    ]
