# Generated by Django 3.2.19 on 2023-05-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points_app', '0003_auto_20230517_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closestpoints',
            name='closest_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closest_point', to='points_app.point'),
        ),
        migrations.AlterField(
            model_name='closestpoints',
            name='original_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_points', to='points_app.point'),
        ),
    ]
